"""added user_id column to image table

Revision ID: 27ce56bd107b
Revises: 60aa63e79f52
Create Date: 2024-03-24 14:36:19.116949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27ce56bd107b'
down_revision = '60aa63e79f52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('user_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'image', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'image', type_='foreignkey')
    op.drop_column('image', 'user_id')
    # ### end Alembic commands ###
